### ISSUE TITLE
panic_observable_is_less assumes sorting algorithm does not use fewer comparisons for invalid inputs

### ISSUE THREAD

**Issue by orlp** [Voultapher/sort-research-rs#1]
Hey, glidesort passes all your tests except one. However I believe the test to check for things that the sorting interface does not guarantee at all.

This check is the problematic one: https://github.com/Voultapher/sort-research-rs/blob/main/tests/main.rs#L853

Glidesort uses different amounts of memory and thus has different behavior for differently sized objects. You can't count the number of comparisons directly on `i32` and then pass it something else and expect it to use the same number of comparisons.

**Comment by Voultapher** [comment]
Hi, yeah that test is quite fresh and my ipn_stable and ipn_unstable fail it also, I haven't gotten around taking a closer look yet. I agree that it should use the same type to calculate the required comparisons.

**Comment by Voultapher** [comment]
I've pushed https://github.com/Voultapher/sort-research-rs/commit/e217452df5d510c5291f0c3949631c7cfaa8d9e0 please let me know if this seems like an appropriate fix.

**Comment by orlp** [comment]
I think that'd work for glidesort, but not for sorts which are non-deterministic. I would honestly just eliminate the `assert!(res.is_err());` entirely.

**Comment by Voultapher** [comment]
The main goal of this test suite, is to validate a sort implementation for adoption in the Rust standard library. I would be surprised if that would ever be allowed to be non-deterministic. The majority of available sorts in the repository fails some tests, no C or C++ sort passes the simpler panic_retain_original_set. So I'm fine with this constrain for now.
