### ISSUE TITLE
The intel-simd-sort is not up to date

### ISSUE THREAD

**Issue by psvri** [Voultapher/sort-research-rs#10]
Hello,

This is more of an FYI than an issue.

There was a [fairly recent PR](https://github.com/intel/x86-simd-sort/pull/33) merged in the repo which shows a large increase in performance. I see that the [current files](https://github.com/Voultapher/sort-research-rs/tree/main/src/cpp/thirdparty/intel_avx512) do not contain these changes.

**Comment by Voultapher** [comment]
Hi, thanks for reaching out. Feel free to open a PR that updates the files. As general note, I don't plan on keeping every of the 20+ vendored sort implementations up-to-date all the time. This repository is meant as a research test bed, and for example right now I'm not doing much with manually vectorized implementations. That said I might update some of them from time to time to see if interesting things happened to learn from. And I'm open to merging PRs that update implementations.
