### ISSUE TITLE
Clarify requirements for new benchmarks or other contributions

### ISSUE THREAD

**Issue by laundmo** [Voultapher/sort-research-rs#21]
Some querstions which could be addressed either in the Readme or a specific Contributing document:

- Which classes and categories of sorts are welcome? which aren't?
- Is there a requirement for popularity/quality of a new sort?
- Should different implementations of the same algorithm be added?
- Should a issue be created to discuss the addition of a sort before starting work on a PR?

**Comment by Voultapher** [comment]
Thanks for bringing them up, I think it would be a good addition to to the project to have a rough contribution guideline for new sort implementations added by others. A draft:

```md
### What to consider when adding a new sort implementation

* The maintainer of this project is currently not interested in building an up-to-date database of all existing sort implementations. Implementations are added based on situational context and relevance to the maintainers' goals.
* Please open an issue before creating a PR that adds a new implementation. Every new implementation adds a significant amount of maintenance effort.
* This project is currently only interested in analyzing single-threaded CPU based implementations or single-threaded variations of multi-threaded CPU based implementations.
* It is expected that new implementations at minimum pass all functionality tests for their supported types. They don't have to pass all safety tests as outlined [here](https://github.com/Voultapher/sort-research-rs/blob/main/writeup/sort_safety/text.md).
* Popularity of new sort implementations is not deemed important.
```

I think the README Contributing section would be a good fit for those.

**Comment by laundmo** [comment]
Hmm, i think theres a lot of fluff here. I think something more concise makes more sense. Theres also nothing about kind of sort you *do* want.

Heres my idea:

> ### New sort implementation requirements

> Please open a PR before spending effort adding a new sort implementation. This repo is not meant as a collection of all implementations.

> Here are the rough requirements for a sort to be considered:
> - Single-Threaded CPU based.
> - Unique or otherwise noteworthy, not a simple reimplementation of a already listed algorithm. (this line makes sense to me but its your repo)
> - Passes all functionality tests for supported types.
> - Does not need to pass all safety tests: [read more](https://github.com/Voultapher/sort-research-rs/blob/main/writeup/sort_safety/text.md).
> - Does not need to be popular/widely used.

```

**Comment by Voultapher** [comment]
Hi, I've opened https://github.com/Voultapher/sort-research-rs/pull/22, I went with a bit a different way than the suggested one. The core message and focus is, "open a PR before" and then let's discuss, adding any specifics about what I'm looking for seem like slippery slope, and generally I'm not even against parallel, GPU, NPU? etc. implementations. Generic rules will just be a good fit, so I wrote down what I expect as baseline and future contributers hopefully read the section and open an issue, where the topic can be discussed with nuance and context. Please let me know if this addresses the issue.

**Comment by Voultapher** [comment]
I'm closing this issue, feel free to re-open it if you think the issue has not been resolved.
