### ISSUE TITLE
Implement optimizations from Stavenga's article

### ISSUE THREAD

**Issue by safinaskar** [Voultapher/sort-research-rs#4]
Please, use optimizations from this cool @gerben-stavenga's article: https://blog.reverberate.org/2020/05/29/hoares-rebuttal-bubble-sorts-comeback.html

**Comment by Voultapher** [comment]
I will take a look, thanks for sharing.

**Comment by Voultapher** [comment]
I added the code from the blog to the repository https://github.com/Voultapher/sort-research-rs/commit/ba34314de1380028ae98bb71f6fc8aa40f0c50ea and after some tweaking get ~101us for hot-u64-10k, also note that the code is not adaptive at all. Using the described portioning scheme is a bit slower than block partion and fulcrum partition.
