### ISSUE TITLE
SingeliSort?

### ISSUE THREAD

**Issue by mlochbaum** [Voultapher/sort-research-rs#5]
I seem to be working on sorting again, so I ought to ask: do you have any interest in reviewing [SingeliSort](https://github.com/mlochbaum/SingeliSort)? I think of it as a quicksort (fluxsort/crumsort) hybrid with many base cases, and a glidesort-ish layer on top. Because of the Robin Hood base case it's much faster than fluxsort on random data, up to 3x or so for i32 in the 1e3 to 1e4 range.

There are still a few improvements I'd like to make, most importantly some kind of adaptive merge instead of always using the branchless one. Also considering an initial sample to skip the glidesort layer if there are many duplicates, which would fix the degradation you've observed in your scaling-random_p benchmark.

While I think results at this stage would still be interesting and mostly remain applicable, the main reason to ask now is to check if there's anything I can do to make SingeliSort more accessible, for benchmarking or in terms of source code. I do intend to add to the README describing the various parts and how they're related, as well as giving some guidance on how to read the source.

**Comment by Voultapher** [comment]
Hi, thanks for reaching out. I'm certainly interested in adding it to the 20+ sorts I have in here already. Doing a full analysis writeup is really time consuming so I can't make any promises there. Looking at the repo, my first issue was it's not documented how to use it, reverse engineering it seems like `sort64` doesn't exist? Or at least not in the precompiled version. I compile all C/C++ implementations as C++ to allow my test and integration suite to work correctly, but doing so with SingeliSort gives me with gcc:

```
cargo:warning=sort-research-rs/src/cpp/thirdparty/singelisort/sort.c:12467:1: error: jump to label ‘l43’
cargo:warning=12467 | l43:;
cargo:warning=      | ^~~
cargo:warning=sort-research-rs/src/cpp/thirdparty/singelisort/sort.c:12458:21: note:   from here
cargo:warning=12458 |   if (!(v161)) goto l43;
cargo:warning=      |                     ^~~
cargo:warning=sort-research-rs/src/cpp/thirdparty/singelisort/sort.c:12466:10: note:   crosses initialization of ‘double v166’
cargo:warning=12466 |   double v166 = v7_dpos[v12_half] = v162_l;
```

Compiling as C++ would a pre-requisite for me to add it into the repo.

**Comment by mlochbaum** [comment]
Yes, 64-bit int sorting isn't defined, only 64-bit float `sort_f64`. I just added a few more instructions including where to see the exported functions (bottom of src/sort.singeli on the Singeli side, bottom of sort.c in C). It's easy to add with `export{'sort64',   glide_sort{up, i64}}` and I think I tested it at some point...

I'll look at having Singeli's code generator move declarations up to the top of the function, maybe under a compilation flag `--cpp-compat` or something.

**Comment by mlochbaum** [comment]
I've added the option `-t cpp` (short for `--target cpp`) to Singeli, and used it for compiled/sort.c. So bench.c now compiles with g++. Also added `sort64`.

Turns out that simply splitting a variable declaration like `int32_t v1_b =` into `int32_t v1_b; v1_b =` is enough. The ugly part was arrays: no assignment so I had to declare another array and copy it over in a block. This is only used to make temp space in some merging stuff, and I don't see a change in overall performance, so either the compiler optimizes it properly or it just takes negligible time.

**Comment by Voultapher** [comment]
Thanks, I created a PR https://github.com/Voultapher/sort-research-rs/pull/6 running my test suite with what is supported by the lack of custom comparison function yielded crashes. More details in the PR.

**Comment by Voultapher** [comment]
It has been added, closing this.

**Comment by mlochbaum** [comment]
Indeed and thank you very much! I'll send you the heads up when I have a version I consider more finished.
