### ISSUE TITLE
Old module references in fuzz testers

### ISSUE THREAD

**Issue by mlochbaum** [Voultapher/sort-research-rs#8]
Both fuzz testers use `sort_comp::stable::rust_ipn` instead of `sort_comp::unstable::rust_ipnsort`. Also I see some changes in Cargo.lock when building, if you want to keep this up to date.

I'd also find it helpful to have the commands `cargo install cargo-fuzz` and `cargo install afl` listed in the README to get started quicker.

Naturally my goal is to run these on SingeliSort. The obvious replacement isn't working right away so I guess I'll need to actually figure out how some of this stuff works, but I'd appreciate any quick comments you have!

**Comment by Voultapher** [comment]
True haven't used them in a while. Updated it now.

> I'd also find it helpful to have the commands cargo install cargo-fuzz and cargo install afl listed in the README to get started quicker.

I think that's coverd by 

> You'll need to install cargo fuzz and cargo afl respectively.
See https://rust-fuzz.github.io/book/introduction.html.

> Naturally my goal is to run these on SingeliSort. The obvious replacement isn't working right away so I guess I'll need to actually figure out how some of this stuff works, but I'd appreciate any quick comments you have!

I suspect you'll find more stuff with libfuzzer, but that requires deep compiler integration. For sort implementations written in Rust it's a drop in replacement, but that's not gonna work for C/C++ stuff. My recommendation would be to look at resources how to get libfuzzer running in a C++ context.

**Comment by mlochbaum** [comment]
The rust-fuzz link is how I found those commands, but I thought it'd be nicer not having to click through just to find the package names.
